import { imageRetrieve } from "./imageRetrive"

export const countryInfo = [
    {
        id: 0,
        country: 'Colombia',
        subtitle: 'Rhythm, Coffee, and Paisa Charm',
        description: 'From the colorful streets of Cartagena to \nthe lush coffee valleys of Salento, Colombia\n is a country that pulses with life. Dance to \nthe rhythm of cumbia and reggaetón, and \nimmerse yourself in a culture known for its \nwarmth and passion.',
        motive: 'Speak Like a Parce, No Joda!',
        buttonText: 'Enroll for free!',
        images: imageRetrieve('home/co/'),
        margin: 0,
        infoSide: 0,
        bgPhoto: '',
        bgText: ''
    },
    {
        id: 1,
        country: 'Perú',
        subtitle: 'Ancient Wonders and\n Culinary Magic',
        description: 'From the mystical ruins of Machu Picchu \nto the bustling food markets of Lima, Perú\n is a land of ancient history and world-class\n cuisine. Discover its Incan heritage,\n breathtaking landscapes, and legendary\n gastronomy.',
        motive: 'Speak Like a Peruano, Causa! \n Learn Peruvian Spanish today!',
        buttonText: 'Get started',
        images: imageRetrieve('src/assets/home/pe/'),
        margin: 0,
        infoSide: 0,
        bgPhoto: '',
        bgText: ''
    },
    {
        id: 3,
        country: 'Argentina',
        subtitle: 'Tango, Passion, and Mate',
        description: 'From the bohemian streets of Buenos Aires to\n the jaw-dropping peaks of Patagonia,\n Argentina is a country of rhythm, soul, and \nadventure. Sip on mate, dance tango, and dive\n into fútbol culture like a true Porteño.',
        motive: 'Learn Argentinian Spanish and lunfardo slang with\n AI-powered lessons. Enroll for free and start\n sounding like a native today!',
        buttonText: 'Enroll',
        images: imageRetrieve('src/assets/home/ar/'),
        margin: 0,
        infoSide: 0,
        bgPhoto: '',
        bgText: ''
    },
    {
        id: 3,
        country: 'Spain',
        subtitle: 'History, Flamenco, and Fiesta',
        description: 'From the majestic Alhambra to the sun-\nsoaked beaches of Ibiza, Spain is a land\n of deep history, rich culture, and\n unforgettable nights. Experience\n flamenco, tapas, and vibrant local fiestas\n in every corner.',
        motive: 'Talk Like a Madrileño or Andaluz!',
        buttonText: 'Begin learning!',
        images: imageRetrieve('src/assets/home/es/'),
        margin: 0,
        infoSide: 0,
        bgPhoto: '',
        bgText: ''
    },
    {
        id: 4,
        country: 'Venezuela',
        subtitle: 'Caribbean Sun and Soul',
        description: 'From the Caribbean beaches of Los\n Roques to the towering Angel Falls,\n Venezuela is a country of rich landscapes,\n lively culture, and passionate people. Feel\n the energy of gaitas, salsa, and arepas on\n every street corner.',
        motive: 'Speak Venezolano, Vale!',
        buttonText: 'Start',
        images: imageRetrieve('src/assets/home/ve/'),
        margin: 0,
        infoSide: 0,
        bgPhoto: '',
        bgText: ''
    },
    {
        id: 5,
        country: 'Puerto Rico',
        subtitle: 'Island Vibes and Reggaetón',
        description: 'From the cobblestone streets of Old San\n Juan to the pristine beaches of Culebra,\n Puerto Rico is a paradise of music, flavor,\n and natural beauty. Feel the energy of\n reggaetón, salsa, and the island’s rich\n culture wherever you go.',
        motive: 'Speak Boricua, Dale Pa’lante!',
        buttonText: 'Sign me up!',
        images: imageRetrieve('src/assets/home/pr/'),
        margin: 0,
        infoSide: 0,
        bgPhoto: '',
        bgText: ''
    },
    {
        id: 6,
        country: 'México',
        subtitle: 'Culture, Flavor, and Fiesta',
        description: "From the bustling streets of CDMX to the\n crystal-clear cenotes of the Yucatán, Mexico is\n a land of ancient history, vibrant traditions, and\n mouthwatering cuisine. Whether you're\n exploring Mayan ruins, mariachi-filled plazas, or\n Día de los Muertos celebrations, Mexico is a\n place where every moment feels alive.",
        motive: 'Speak Like a Chilango or a Tapatío—For Free!',
        buttonText: 'Join now',
        images: imageRetrieve('src/assets/home/me/'),
        margin: 0,
        infoSide: 0,
        bgPhoto: '',
        bgText: ''
    },
    {
        id: 7,
        country: 'Ecuador',
        subtitle: 'Andes, Amazon, and Coastal Charm',
        description: "Ecuador is where the Amazon, the Andes, and the\n Pacific collide. Walk through Quito’s colonial streets,\n explore the Galápagos, or sip on canelazo in the\n highlands—every corner of Ecuador is packed with\n beauty and culture.",
        motive: 'Speak Like an Ecuatoriano, De Una!',
        buttonText: 'Start learning',
        images: imageRetrieve('src/assets/home/ec/'),
        margin: 0,
        infoSide: 0,
        bgPhoto: '',
        bgText: ''
    },
    {
        id: 8,
        country: 'Dominican Republic',
        subtitle: 'Merengue, Beaches, and Cultura',
        description: "With its turquoise waters, lively merengue, and\n vibrant street life, the Dominican Republic is a\n place of energy, warmth, and Afro-Caribbean\n soul. Whether you're in Santo Domingo or Punta\n Cana, the island’s rhythm is unmistakable.",
        motive: 'Speak Like a Dominicano, No Bulto!',
        buttonText: 'Get started',
        images: imageRetrieve('src/assets/home/dr/'),
        margin: 0,
        infoSide: 0,
        bgPhoto: '',
        bgText: ''
    }
]